import{S as c,N as d,K as m,M as p,P as h,a as v}from"./assets/vendor-ffbced06.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();c.use([d,m,p,h]);new c(".swiper-about-me",{slidesPerView:"auto",breakpoints:{375:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:5}},initialSlide:0,loop:!0,autoplay:{delay:5e3},grabCursor:!0,keyboard:!0,mousewheel:{invert:!0},navigation:{nextEl:".btn-next"},navigationPosition:"right",effect:"fade",allowSlidePrev:!1,on:{slideChange:function(){document.querySelector(".swiper-slide.skills-item-wrap-activ").classList.remove("skills-item-wrap-activ"),this.slides[this.activeIndex].classList.add("skills-item-wrap-activ")}}});c.use([d,m,p]);new c(".swiper-projects",{slidesPerView:"auto",loop:!1,speed:400,grabCursor:!0,spaceBetween:16,slidesPerView:1,keyboard:{enabled:!0},navigation:{nextEl:".btn-next",prevEl:".btn-prev"},mousewheel:{sensitivity:1},on:{reachEnd:function(){document.querySelector(".btn-prev").classList.remove("no-active"),document.querySelector(".btn-next").classList.add("no-active")},reachBeginning:function(){document.querySelector(".btn-next").classList.remove("no-active"),document.querySelector(".btn-prev").classList.add("no-active")}}});function g(e){document.querySelectorAll(".marquee__inner img").forEach(s=>{e?s.classList.add("running"):s.classList.remove("running")})}const b=document.querySelector(".covers"),L=.4,S={threshold:L},q=new IntersectionObserver(e=>{e.forEach(t=>{g(t.isIntersecting)})},S);q.observe(b);async function E(){const t="https://portfolio-js.b.goit.study/api/reviews";try{return(await v.get(t)).data}catch(s){throw console.error("Error fetching reviews:",s),s}}async function P(e){const s="https://portfolio-js.b.goit.study/api/requests";try{return(await v.post(s,e)).data}catch(i){throw console.error("Error posting request:",i),i}}new c;function B({author:e,avatar_url:t,review:s}){return`<li class="reviews-list-item swiper-slide">
          <a class="reviews-image" href='${t}'>
            <img src='${t}' alt="avatar author" class="photo-img" />
          </a>
          <h3 class="reviews-title-name">${e}</h3>
          <p class="reviews-text">${s}
          </p>
        </li>`}function R(e){return e.map(B).join(" ")}window.onload=x;const A=document.querySelector(".reviews-list");async function x(){try{const e=await E();console.log(e);const t=R(e);A.innerHTML=t}catch(e){console.log(e)}}const y=document.querySelector(".form"),f=document.getElementById("email"),I=document.getElementById("comment");document.querySelector(".submit-btn");const r=document.querySelector(".modal-overlay"),a=document.querySelector(".modal-window"),k=document.querySelector(".modal-btn-close");f.addEventListener("input",function(){const e=this.value;/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(e)?(this.classList.remove("input-error"),this.classList.add("input-success")):(this.classList.remove("input-success"),this.classList.add("input-error"))});y.addEventListener("submit",O);async function O(e){e.preventDefault();const t={email:f.value,comment:I.value};try{(await P(t)).title!==" "&&(r.style.opacity=1,r.style.visibility="visible",a.style.opacity=1,a.style.visibility="visible",y.reset())}catch(s){throw s}}k.addEventListener("click",u);function u(){r.style.opacity=0,r.style.visibility="hidden",a.style.opacity=0,a.style.visibility="hidden"}r.addEventListener("click",u);window.addEventListener("keydown",e=>{e.key==="Escape"&&u()});const V=document.querySelector(".menu-btn"),$=document.querySelector(".menu-nav"),N=document.querySelectorAll(".menu-nav li a");document.querySelector(".order-button");function w(){$.classList.toggle("show-menu")}V.addEventListener("click",function(){w()});N.forEach(e=>e.addEventListener("click",_));function _(e){w()}
//# sourceMappingURL=commonHelpers.js.map
